# Generated by Django 5.1.5 on 2025-02-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('exercise', models.CharField(max_length=200, verbose_name='Ćwiczenie')),
                ('sets', models.PositiveIntegerField(verbose_name='Serie')),
                ('reps', models.PositiveIntegerField(verbose_name='Powtórzenia')),
                ('weight', models.FloatField(help_text='Waga użyta podczas ćwiczenia', verbose_name='Waga (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
